import { StyleSheet } from 'react-native';

import type { AppTheme } from '@shared/theme';

export const createToolCardStyles = (theme: AppTheme) =>
  StyleSheet.create({
    rowLayoutClip: { overflow: 'hidden' },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      minHeight: 26,
      paddingVertical: 5,
      borderRadius: theme.radius.sm,
    },
    rowPressed: { backgroundColor: theme.colors.bgCanvasAccent },
    rowTouchTarget: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      borderRadius: theme.radius.sm,
    },
    rowError: {
      backgroundColor: theme.colors.errorBg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.errorBorder,
    },
    rowRegion: {
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 18,
    },
    rowIcon: {
      width: 16 + theme.spacing.sm,
      paddingLeft: theme.spacing.sm,
    },
    rowContent: { flex: 1, minWidth: 0 },
    rowContentPressable: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingLeft: theme.spacing.sm,
    },
    rowAction: {
      ...theme.typography.caption,
      color: theme.colors.textMuted,
      lineHeight: 16,
      flexShrink: 0,
    },
    rowSubject: {
      ...theme.typography.caption,
      color: theme.colors.textMuted,
      lineHeight: 16,
      flexShrink: 1,
    },
    rowSubjectMono: {
      fontFamily: theme.fonts.monoRegular,
      flexShrink: 0,
      paddingRight: theme.spacing.lg,
    },
    rowTitleError: { color: theme.colors.statusError },
    rowTextHighlight: { color: theme.colors.textPrimary },
    rowTrailing: {
      minWidth: 18 + theme.spacing.sm * 2,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-end',
      gap: 4,
      paddingLeft: theme.spacing.sm,
      paddingRight: theme.spacing.sm,
    },
    horizontalScrollFrame: { flex: 1, minWidth: 0, position: 'relative' },
    commandScroll: { flex: 1, minWidth: 0 },
    commandScrollContent: { flexDirection: 'row', flexGrow: 1 },
    commandPressable: {
      flexGrow: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingLeft: theme.spacing.sm,
    },
    panel: {
      marginLeft: theme.spacing.sm,
      marginTop: theme.spacing.xs,
      marginBottom: theme.spacing.xs,
      borderRadius: theme.radius.md,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.borderLight,
      backgroundColor: theme.colors.bgCanvasAccent,
      overflow: 'hidden',
    },
    panelScroll: { maxHeight: 300 },
    panelSection: {
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
      gap: theme.spacing.xs,
    },
    panelDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: theme.colors.borderLight,
    },
    sectionLabel: {
      ...theme.typography.metadata,
      color: theme.colors.textMuted,
    },
    timingMetrics: {
      flexDirection: 'row',
      gap: theme.spacing.lg,
    },
    timingMetric: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    timingLabel: {
      ...theme.typography.metadata,
      color: theme.colors.textMuted,
    },
    timingValue: {
      ...theme.typography.caption,
      color: theme.colors.textSecondary,
    },
    timingDuration: {
      fontVariant: ['tabular-nums'],
    },
    outputSurface: {
      paddingVertical: theme.spacing.xs,
      gap: 2,
    },
    consoleSurface: {
      paddingHorizontal: theme.spacing.sm,
      borderRadius: theme.radius.sm,
      backgroundColor: theme.colors.bgElevated,
    },
    outputLine: {
      ...theme.typography.mono,
      lineHeight: 16,
      color: theme.colors.textSecondary,
    },
    locationChips: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: theme.spacing.xs,
    },
    locationChip: {
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: theme.radius.sm,
      backgroundColor: theme.colors.inlineCodeBg,
    },
    locationChipText: {
      ...theme.typography.metadata,
      fontFamily: theme.fonts.monoRegular,
      color: theme.colors.textMuted,
    },
    diffBlock: {
      overflow: 'hidden',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.borderLight,
      borderRadius: theme.radius.sm,
    },
    diffBlockSeparated: { marginTop: theme.spacing.sm },
    diffFileHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: theme.spacing.sm,
      minHeight: 28,
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.xs,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.borderLight,
      backgroundColor: theme.colors.bgElevated,
    },
    diffFilePath: {
      ...theme.typography.metadata,
      fontFamily: theme.fonts.monoRegular,
      color: theme.colors.textMuted,
      flex: 1,
    },
    diffStats: {
      flexDirection: 'row',
      gap: theme.spacing.xs,
    },
    diffStat: {
      ...theme.typography.metadata,
      minWidth: 24,
      textAlign: 'center',
      fontWeight: '700',
    },
    diffAddedStat: {
      color: theme.colors.diffAddedText,
    },
    diffRemovedStat: {
      color: theme.colors.diffRemovedText,
    },
    diffScrollContent: { minWidth: '100%' },
    diffScrollFrame: {
      position: 'relative',
      paddingVertical: 2,
    },
    diffLines: { minWidth: '100%' },
    diffLine: {
      flexDirection: 'row',
      alignItems: 'stretch',
      minWidth: '100%',
    },
    diffLineAdded: { backgroundColor: theme.colors.diffAddedBg },
    diffLineRemoved: { backgroundColor: theme.colors.diffRemovedBg },
    diffLineMarker: {
      ...theme.typography.mono,
      width: 22,
      lineHeight: 17,
      paddingVertical: 1,
      color: theme.colors.textMuted,
      textAlign: 'center',
      fontWeight: '800',
      borderLeftWidth: 3,
      borderLeftColor: theme.colors.borderLight,
      borderRightWidth: StyleSheet.hairlineWidth,
      borderRightColor: theme.colors.borderLight,
    },
    diffLineMarkerAdded: {
      color: theme.colors.diffAddedText,
      borderLeftColor: theme.colors.diffAddedText,
    },
    diffLineMarkerRemoved: {
      color: theme.colors.diffRemovedText,
      borderLeftColor: theme.colors.diffRemovedText,
    },
    diffLineText: {
      ...theme.typography.mono,
      color: theme.colors.textPrimary,
      lineHeight: 17,
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: 1,
      flexShrink: 0,
    },
    diffBlockNote: {
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.xs,
    },
    syntaxComment: { color: theme.colors.codeSyntaxComment },
    syntaxKeyword: { color: theme.colors.codeSyntaxKeyword },
    syntaxString: { color: theme.colors.codeSyntaxString },
    syntaxNumber: { color: theme.colors.codeSyntaxNumber },
    syntaxFunction: { color: theme.colors.codeSyntaxFunction },
    syntaxProperty: { color: theme.colors.codeSyntaxProperty },
    syntaxOperator: { color: theme.colors.codeSyntaxOperator },
    note: {
      ...theme.typography.metadata,
      color: theme.colors.textMuted,
    },
    errorNote: {
      ...theme.typography.caption,
      color: theme.colors.statusError,
    },
  });
