import { StyleSheet } from 'react-native';

import type { AppTheme } from '../theme';

export const createMainScreenAgentStyles = (theme: AppTheme) => {
  return {
    modelChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      borderRadius: 999,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.borderLight,
      backgroundColor: theme.colors.bgElevated,
      minHeight: 28,
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: 5,
      flexShrink: 0,
    },
    modeChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      borderRadius: 999,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.borderLight,
      backgroundColor: theme.colors.bgElevated,
      minHeight: 28,
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: 5,
      flexShrink: 0,
    },
    fastChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      borderRadius: 999,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.borderLight,
      backgroundColor: theme.colors.bgElevated,
      minHeight: 28,
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: 5,
      flexShrink: 0,
    },
    fastChipEnabled: { borderColor: theme.colors.successBorder, backgroundColor: theme.colors.successBg },
    modelChipPressed: { opacity: 0.86 },
    sessionMetaChipDisabled: { opacity: 0.5 },
    modelChipText: { ...theme.typography.caption, color: theme.colors.textSecondary, fontSize: 11, lineHeight: 14, fontWeight: '600' },
    inlineOptionsGroup: {
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: theme.colors.borderLight,
      backgroundColor: theme.colors.bgMain,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
      gap: theme.spacing.sm,
      maxHeight: 320,
    },
    inlineOptionsHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: theme.spacing.sm },
    inlineOptionsTitle: { ...theme.typography.body, color: theme.colors.textPrimary, fontWeight: '700' },
    inlineOptionsClose: { width: 28, height: 28, alignItems: 'center', justifyContent: 'center', borderRadius: 6 },
    inlineOptionsScroll: { flexGrow: 0 },
    inlineOptionsContent: { gap: theme.spacing.xs },
    inlineOptionsLoading: { minHeight: 44, flexDirection: 'row', alignItems: 'center', gap: theme.spacing.sm },
    inlineOption: {
      minHeight: 46,
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.sm,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.borderLight,
      borderRadius: 8,
      backgroundColor: theme.colors.bgItem,
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.xs,
    },
    inlineOptionSelected: { borderColor: theme.colors.borderHighlight, backgroundColor: theme.colors.bgInput },
    inlineOptionDisabled: { opacity: 0.45 },
    inlineOptionPressed: { opacity: 0.84 },
    inlineOptionCopy: { flex: 1, minWidth: 0, gap: 2 },
    inlineOptionTitle: { ...theme.typography.body, color: theme.colors.textPrimary, fontSize: 13, lineHeight: 18, fontWeight: '600' },
    inlineOptionsDescription: { ...theme.typography.caption, color: theme.colors.textMuted, fontSize: 11, lineHeight: 15 },
    fastChipTextEnabled: { color: theme.colors.textPrimary },
  } as const;
};