import { StyleSheet } from 'react-native';

import type { AppTheme } from '@shared/theme';

export const createMainScreenConversationStyles = (theme: AppTheme) =>
  ({
    composeScroll: { flex: 1 },
    composeContainer: {
      flexGrow: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: theme.spacing.xl,
      paddingBottom: theme.spacing.xxl * 2,
    },
    composeContainerKeyboardOpen: {
      justifyContent: 'flex-start',
      paddingTop: theme.spacing.xl,
      paddingBottom: theme.spacing.xl,
    },
    composeIcon: { marginBottom: theme.spacing.lg },
    composeTitle: {
      ...theme.typography.largeTitle,
      marginBottom: theme.spacing.xl,
    },
    workspaceSelectBtn: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.sm,
      borderRadius: theme.radius.md,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.borderLight,
      backgroundColor: theme.colors.bgItem,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
      marginBottom: theme.spacing.xl * 2,
    },
    workspacePathSelectBtn: {
      alignItems: 'flex-start',
      paddingTop: theme.spacing.md,
      paddingBottom: theme.spacing.md,
    },
    workspaceSelectBtnPressed: { opacity: 0.85 },
    workspaceSelectLabel: {
      ...theme.typography.caption,
      color: theme.colors.textSecondary,
      flex: 1,
    },
    workspacePathSelectLabel: { flexShrink: 1, lineHeight: 18 },
    suggestions: { flexDirection: 'row', gap: theme.spacing.md, width: '100%' },
    suggestionCard: {
      flex: 1,
      backgroundColor: theme.colors.bgItem,
      borderWidth: 1,
      borderColor: theme.colors.border,
      borderRadius: theme.radius.md,
      padding: theme.spacing.md,
    },
    suggestionCardPressed: { backgroundColor: theme.colors.bgInput },
    suggestionText: {
      ...theme.typography.caption,
      color: theme.colors.textPrimary,
      lineHeight: 18,
    },
    messageListShell: { flex: 1 },
    messageList: { flex: 1 },
    transcriptEdgeScrim: {
      position: 'absolute',
      right: 0,
      left: 0,
      zIndex: 1,
    },
    jumpToLatestButton: {
      position: 'absolute',
      alignSelf: 'center',
      zIndex: 2,
    },
    jumpToLatestGlass: {
      alignItems: 'center',
      justifyContent: 'center',
      borderCurve: 'continuous',
      borderRadius: theme.radius.full,
      width: 48,
      height: 48,
      boxShadow: theme.isDark
        ? '0 12px 24px rgba(0, 0, 0, 0.28)'
        : '0 10px 22px rgba(15, 31, 54, 0.12)',
    },
    jumpToLatestButtonInner: {
      alignItems: 'center',
      justifyContent: 'center',
      width: 48,
      height: 48,
      borderRadius: theme.radius.full,
    },
    jumpToLatestButtonPressed: { transform: [{ scale: 0.96 }] },
    messageListContent: {
      flexGrow: 1,
      padding: theme.spacing.lg,
      paddingTop: theme.spacing.lg,
      paddingBottom: theme.spacing.xl,
      gap: theme.spacing.xl,
    },
    chatMessageBlock: { gap: theme.spacing.sm },
    inlineChoiceOptions: { marginLeft: theme.spacing.sm, gap: theme.spacing.xs },
    inlineChoiceOptionButton: {
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.border,
      backgroundColor: theme.colors.bgItem,
      borderRadius: 10,
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: theme.spacing.sm,
      gap: 2,
    },
    inlineChoiceOptionButtonPressed: {
      backgroundColor: theme.colors.bgInput,
      borderColor: theme.colors.borderHighlight,
    },
    inlineChoiceOptionRow: { flexDirection: 'row', alignItems: 'center', gap: theme.spacing.sm },
    inlineChoiceOptionIndex: {
      ...theme.typography.caption,
      color: theme.colors.textMuted,
      fontWeight: '700',
      minWidth: 18,
    },
    inlineChoiceOptionLabel: {
      ...theme.typography.caption,
      color: theme.colors.textPrimary,
      fontWeight: '600',
      flex: 1,
    },
    inlineChoiceOptionDescription: { ...theme.typography.caption, color: theme.colors.textMuted },
    inlineChoiceHint: {
      ...theme.typography.caption,
      color: theme.colors.textMuted,
      marginTop: 2,
      marginLeft: theme.spacing.xs,
    },
    chatOpeningShell: {
      flex: 1,
      backgroundColor: theme.colors.bgElevated,
      paddingHorizontal: theme.spacing.lg,
      paddingTop: theme.spacing.lg,
    },
    chatOpeningCard: {
      borderRadius: theme.radius.lg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.borderLight,
      backgroundColor: theme.colors.bgItem,
      padding: theme.spacing.md,
      gap: theme.spacing.md,
    },
    chatOpeningTopRow: {
      minHeight: 24,
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.sm,
    },
    chatOpeningTitle: {
      ...theme.typography.caption,
      color: theme.colors.textSecondary,
      fontWeight: '700',
    },
    chatOpeningBubbleWide: {
      width: '82%',
      height: 18,
      borderRadius: theme.radius.full,
      backgroundColor: theme.colors.bgInput,
    },
    chatOpeningBubbleShort: {
      width: '54%',
      height: 18,
      borderRadius: theme.radius.full,
      backgroundColor: theme.colors.bgInput,
    },
    streamingText: {
      ...theme.typography.body,
      fontStyle: 'italic',
      color: theme.colors.textMuted,
      lineHeight: 20,
    },
    bridgeRecoveryBanner: {
      marginHorizontal: theme.spacing.lg,
      marginBottom: theme.spacing.sm,
      borderRadius: 14,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: theme.colors.borderHighlight,
      backgroundColor: theme.colors.warningBg,
      padding: theme.spacing.md,
      gap: theme.spacing.sm,
    },
    bridgeRecoveryBannerTopRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: theme.spacing.sm,
    },
    bridgeRecoveryBannerIconWrap: {
      width: 24,
      height: 24,
      borderRadius: theme.radius.full,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.bgItem,
    },
    bridgeRecoveryBannerCopy: { flex: 1, gap: 2 },
    bridgeRecoveryBannerTitle: {
      ...theme.typography.body,
      color: theme.colors.textPrimary,
      fontWeight: '700',
    },
    bridgeRecoveryBannerBody: {
      ...theme.typography.caption,
      color: theme.colors.textSecondary,
      lineHeight: 17,
    },
    bridgeRecoveryBannerStatus: {
      ...theme.typography.caption,
      color: theme.colors.textPrimary,
      lineHeight: 17,
    },
    bridgeRecoveryBannerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: theme.spacing.sm,
    },
    bridgeRecoveryBannerButton: {
      alignSelf: 'flex-start',
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.xs,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.colors.accent,
      backgroundColor: theme.colors.accent,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
    },
    bridgeRecoveryBannerButtonPressed: {
      backgroundColor: theme.colors.accentPressed,
      borderColor: theme.colors.accentPressed,
    },
    bridgeRecoveryBannerButtonDisabled: { opacity: 0.72 },
    bridgeRecoveryBannerButtonText: {
      ...theme.typography.caption,
      color: theme.colors.accentText,
      fontWeight: '700',
    },
    bridgeRecoveryBannerSecondaryButton: {
      alignSelf: 'flex-start',
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.colors.borderHighlight,
      backgroundColor: theme.colors.bgItem,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
    },
    bridgeRecoveryBannerSecondaryButtonPressed: { backgroundColor: theme.colors.bgInput },
    bridgeRecoveryBannerSecondaryButtonText: {
      ...theme.typography.caption,
      color: theme.colors.textSecondary,
      fontWeight: '700',
    },
    errorText: {
      ...theme.typography.caption,
      color: theme.colors.error,
      alignSelf: 'stretch',
      backgroundColor: theme.colors.bgElevated,
      borderColor: theme.colors.errorBorder,
      borderRadius: theme.radius.md,
      borderWidth: StyleSheet.hairlineWidth,
      marginHorizontal: theme.spacing.lg,
      paddingHorizontal: theme.spacing.lg,
      paddingVertical: theme.spacing.sm,
      boxShadow: theme.isDark
        ? '0 8px 20px rgba(0, 0, 0, 0.28)'
        : '0 8px 18px rgba(15, 31, 54, 0.12)',
    },
  }) as const;
