import { StyleSheet } from 'react-native';

import type { AppTheme } from '../../theme';

export const createGitCheckoutScreenStyles = (theme: AppTheme) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: theme.colors.bgMain },
    keyboardLayer: { flex: 1 },
    header: {
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: theme.spacing.lg,
      paddingTop: theme.spacing.sm,
    },
    headerSpacer: { width: 36 },
    backButton: {
      width: 36,
      height: 36,
      borderRadius: theme.radius.full,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.colors.bgInput,
      borderWidth: 1,
      borderColor: theme.colors.borderLight,
    },
    pressed: { opacity: 0.86 },
    title: {
      ...theme.typography.title,
      textAlign: 'center',
    },
    body: {
      padding: theme.spacing.lg,
      gap: theme.spacing.md,
    },
    hint: {
      ...theme.typography.caption,
      color: theme.colors.textMuted,
      lineHeight: 18,
    },
    input: {
      minHeight: theme.touchTarget.minimum,
      borderRadius: theme.radius.md,
      borderWidth: 1,
      borderColor: theme.colors.borderLight,
      backgroundColor: theme.colors.bgInput,
      paddingHorizontal: theme.spacing.md,
      color: theme.colors.textPrimary,
      ...theme.typography.body,
    },
    pathButton: {
      minHeight: 52,
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.sm,
      borderRadius: theme.radius.md,
      borderWidth: 1,
      borderColor: theme.colors.borderLight,
      backgroundColor: theme.colors.bgItem,
      paddingHorizontal: theme.spacing.md,
    },
    pathCopy: { flex: 1, minWidth: 0, gap: 2 },
    pathLabel: {
      ...theme.typography.metadata,
      color: theme.colors.textMuted,
      textTransform: 'uppercase',
      letterSpacing: 0,
    },
    pathValue: {
      ...theme.typography.body,
      color: theme.colors.textPrimary,
      fontWeight: '600',
    },
    summary: {
      ...theme.typography.caption,
      color: theme.colors.textMuted,
    },
    errorText: {
      ...theme.typography.caption,
      color: theme.colors.error,
      backgroundColor: theme.colors.errorBg,
      borderWidth: 1,
      borderColor: theme.colors.errorBorder,
      borderRadius: theme.radius.sm,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.sm,
    },
    cloningRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.sm,
      paddingVertical: theme.spacing.sm,
    },
    cloningText: {
      ...theme.typography.body,
      color: theme.colors.textSecondary,
    },
    actions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: theme.spacing.sm,
      paddingHorizontal: theme.spacing.lg,
      paddingBottom: theme.spacing.lg,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: theme.colors.borderLight,
      paddingTop: theme.spacing.md,
    },
    button: {
      minWidth: 110,
      minHeight: theme.touchTarget.minimum,
      borderRadius: theme.radius.md,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: theme.spacing.lg,
    },
    buttonSecondary: {
      borderWidth: 1,
      borderColor: theme.colors.borderLight,
      backgroundColor: theme.colors.bgInput,
    },
    buttonSecondaryText: {
      ...theme.typography.body,
      color: theme.colors.textPrimary,
      fontWeight: '600',
    },
    buttonPrimary: { backgroundColor: theme.colors.accent },
    buttonPrimaryText: {
      ...theme.typography.body,
      color: theme.colors.accentText,
      fontWeight: '700',
    },
    buttonDisabled: { opacity: 0.5 },
  });
