declare namespace NodeJS {
  interface ProcessEnv {
    EXPO_PUBLIC_ALLOW_INSECURE_REMOTE_BRIDGE?: string;
    EXPO_PUBLIC_ALLOW_QUERY_TOKEN_AUTH?: string;
    EXPO_PUBLIC_EXTERNAL_STATUS_FULL_SYNC_DEBOUNCE_MS?: string;
    EXPO_PUBLIC_HOST_BRIDGE_TOKEN?: string;
    EXPO_PUBLIC_HOST_BRIDGE_URL?: string;
    EXPO_PUBLIC_IOS_APP_STORE_ID?: string;
    EXPO_PUBLIC_PRIVACY_POLICY_URL?: string;
    EXPO_PUBLIC_TERMS_OF_SERVICE_URL?: string;
  }
}
