import type { AppTheme } from '../theme';
import { TOUCH_TARGET_MINIMUM } from './workspacePickerTouch';

export const createWorkspacePickerLayoutStyles = (theme: AppTheme) => ({
  screen: { flex: 1, backgroundColor: theme.colors.bgMain },
  header: {
    minHeight: 48,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.sm,
  },
  headerSpacer: { width: 36 },
  title: {
    ...theme.typography.headline,
    fontSize: 18,
    fontWeight: '700' as const,
    textAlign: 'center' as const,
  },
  closeButton: {
    width: 36,
    height: 36,
    borderRadius: theme.radius.full,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: theme.colors.bgInput,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
  },
  body: {
    flex: 1,
    paddingHorizontal: theme.spacing.lg,
    paddingBottom: theme.spacing.lg,
    gap: theme.spacing.sm,
  },
  topContentScroll: { flexShrink: 1, flexGrow: 0 },
  topContentContainer: { gap: theme.spacing.sm, paddingBottom: theme.spacing.sm },
  connectionRow: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: theme.spacing.md,
  },
  connectionText: { flex: 1, ...theme.typography.caption, color: theme.colors.textSecondary },
  defaultButton: {
    minHeight: TOUCH_TARGET_MINIMUM,
    paddingHorizontal: theme.spacing.md,
    borderRadius: theme.radius.full,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.bgItem,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  defaultButtonSelected: {
    borderColor: theme.colors.borderHighlight,
    backgroundColor: theme.colors.bgInput,
  },
  defaultButtonText: {
    ...theme.typography.caption,
    color: theme.colors.textSecondary,
    fontWeight: '600' as const,
  },
  defaultButtonTextSelected: { color: theme.colors.textPrimary },
  searchField: {
    minHeight: 36,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
    backgroundColor: theme.colors.bgInput,
    paddingHorizontal: theme.spacing.md,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: theme.spacing.sm,
  },
  searchInput: { flex: 1, ...theme.typography.body, paddingVertical: 0 },
  actionCard: {
    minHeight: TOUCH_TARGET_MINIMUM,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
    backgroundColor: theme.colors.bgItem,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: theme.spacing.sm,
  },
  actionIconWrap: {
    width: 24,
    height: 24,
    borderRadius: theme.radius.full,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    backgroundColor: theme.colors.bgInput,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
  },
  actionCopy: { flex: 1, gap: 2 },
  actionTitle: {
    ...theme.typography.body,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '700' as const,
    color: theme.colors.textPrimary,
  },
  actionSubtitle: {
    ...theme.typography.caption,
    fontSize: 11,
    lineHeight: 15,
    color: theme.colors.textSecondary,
  },
  breadcrumbRow: {
    flexDirection: 'row' as const,
    alignItems: 'flex-start' as const,
    gap: theme.spacing.sm,
  },
  upButton: {
    minHeight: TOUCH_TARGET_MINIMUM,
    marginTop: 2,
    paddingHorizontal: theme.spacing.sm,
    borderRadius: theme.radius.full,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    gap: 6,
    backgroundColor: theme.colors.bgItem,
  },
  upButtonText: {
    ...theme.typography.caption,
    color: theme.colors.textSecondary,
    fontWeight: '600' as const,
  },
  currentFolderChip: {
    flex: 1,
    minWidth: 0,
    minHeight: 32,
    borderRadius: theme.radius.lg,
    borderWidth: 1,
    borderColor: theme.colors.borderLight,
    backgroundColor: theme.colors.bgItem,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.xs,
    justifyContent: 'center' as const,
    gap: 2,
  },
  currentFolderTitle: {
    ...theme.typography.body,
    fontSize: 12,
    lineHeight: 16,
    color: theme.colors.textPrimary,
    fontWeight: '700' as const,
  },
  currentFolderPath: {
    ...theme.typography.mono,
    fontSize: 11,
    lineHeight: 14,
    color: theme.colors.textMuted,
  },
  sectionHeader: {
    minHeight: 20,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    gap: theme.spacing.sm,
  },
  sectionTitle: {
    ...theme.typography.caption,
    fontSize: 11,
    color: theme.colors.textSecondary,
    fontWeight: '600' as const,
    textTransform: 'uppercase' as const,
    letterSpacing: 0,
  },
  favoriteGrid: { flexDirection: 'row' as const, flexWrap: 'wrap' as const, gap: theme.spacing.sm },
  buttonDisabled: { opacity: 0.42 },
  pressed: { opacity: 0.86 },
});
