<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>DapperCode.Core.Tests</RootNamespace>
    <NoWarn>$(NoWarn);CA1861</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NSubstitute" />
    <ProjectReference Include="..\..\src\DapperCode.Core\DapperCode.Core.csproj" />
    <ProjectReference Include="..\DapperCode.ProcessFixture\DapperCode.ProcessFixture.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>
</Project>
